package assets;
import PipelineTools;

// generated by tiles.blend

class Pipeline {
	public static var sheets:Array<Sheet> = [
		new Sheet("64x64.png", 256, 128, 0, 4, 2)
	];

	public static var tiles:Map<String, Tile> = [
		"haxeLogo" => new Tile(64, 64, 0, 0, [
			"sphereRotate" => new Anim(0, 2),
			"sphereToCubic" => new Anim(3, 4)
		]),
		"haxeCat" => new Tile(64, 64, 0, 0, [
			"default" => new Anim(5, 5)
		])
	];
}
